#edit test yml as well if need be
logging:
  level: INFO
  loggers:
    com.udemy: DEBUG

#password
password: password

server:
  applicationConnectors:
    - type: http
      port: 9999
    - type: https
      port: 9990
      keyStorePath: dropbookmarks.keystore
      keyStorePassword: password
      validateCerts: false

database:
  driverClass: org.h2.Driver
  user: sa
  password: sa
  url: jdbc:h2:mem:db1;DB_CLOSE_DELAY=-1
  # any properties specific to your JDBC driver:
  properties:
    charSet: UTF-8
    hibernate.dialect: org.hibernate.dialect.H2Dialect
    hibernate.hbm2ddl.auto: create-drop


